---
- name: Deploy sample java application with build and test
  hosts: localhost
  become: no
  vars:
    ansible_python_interpreter: /opt/homebrew/bin/python3
    docker_api_version: 1.43


  tasks:
    # Create a Dockerfile for the application
    - name: Create Dockerfile
      template:
        src: Dockerfile
        dest: ./app/Dockerfile

    # Build the Docker image
    - name: Build Docker image
      community.docker.docker_image:
        name: sample-java-app
        tag: latest
        build:
          path: ./app
          dockerfile: ./app/Dockerfile
        source: build

        

    # Run the Docker container
    - name: Run Docker container
      docker_container:
        name: sample-java-app
        image: sample-java-app:latest
        ports:
          - "9080:9080"
        detach: true

    # Test the application
    - name: Test application
      shell: curl http://localhost:9080
      register: result

    # Verify application response
    - assert:
        that:
          - "'Hello, World!' in result.stdout"
