---
- name: Deploy sample java application with build and test
  hosts: localhost
  become: no
  vars:
    ansible_python_interpreter: /usr/bin/python3      #/opt/homebrew/bin/python3
      #docker_api_version: 1.43

  tasks:
    # Create a Dockerfile for the application
    - name: Create Dockerfile
      template:
        src: Dockerfile
        dest: ./app/Dockerfile

    # Download application source files
    - name: Copy HelloWorld.java
      template:
        src: HelloWorld.java
        dest: ./app/HelloWorld.java

    # Build the Docker image
    - name: Build Docker image
      community.docker.docker_image:
        name: sample-java-app
        tag: latest
        build:
          path: ./app
          dockerfile: Dockerfile
        source: build

        
    # Run the Docker container
    - name: Run Docker container
      docker_container:
        name: sample-java-app
        image: sample-java-app:latest
        ports:
          - "9999:9999"
        detach: true

    - name: Print Hello world!
      debug:
        msg: Hello world!

